language: rust
cache: cargo

os:
  - linux
  - osx
  
rust:
  - stable

script:
     - cargo test --verbose
     - if [ "$TRAVIS_BRANCH" == "master" ]; then echo "Working on master branch" && cargo package --verbose; fi
