[package]
name = "sounding-validate"
version = "0.0.2"
authors = ["Ryan Leach <clumsycodemonkey@gmail.com>"]
description = """Validation of soundings from the sounding-base crate."""
repository = "https://github.com/rnleach/sounding-validate.git"
readme = "README.md"
license-file = "LICENSE"
exclude = ["**/*.rs.bk",".gitignore",".vscode/**/*"]
categories = ["science"]
keywords = ["weather","sounding","meteorology", "skew-t"]

[dependencies]
sounding-base = "^0.0.15"
error-chain = "^0.11"
